// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupExperimentPrefs.dom.push.alwaysConnect", true);
user_pref("app.normandy.startupRolloutPrefs.browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts", true);
user_pref("app.normandy.user_id", "813f8500-972d-4bb4-b654-2e0c0cfee61a");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1544895072);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1544895192);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1544744234);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1544753526);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1544744380);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1544894782);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1544895433);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1544895313);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 788480);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1544744203);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"784\":[1544744207397,1544744351928,1544753498827]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{b83eeddf-cdec-4383-9f8b-098b263ec7b7}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google,amazon");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1544850000);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true},{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1544894759903");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1544896540903");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1544894760224");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1544898360224");
user_pref("browser.search.region", "US");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181207224003");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1544895047");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20181207224003");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"toolbar-menubar\":[\"menubar-items\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":15,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1544744207942");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "976a7cb9c0d844ee8d5cea9af1dfd310");
user_pref("extensions.blocklist.lastModified", "Fri, 14 Dec 2018 18:16:38 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.cache.lastUpdate", 1544895074);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181207224003");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{1e94fb4a-dd6c-4188-85c1-cfdd31ab2ef9}\",\"addons\":{\"fxmonitor@mozilla.org\":{\"version\":\"2.8\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"ac96eab6-d6a5-4470-983b-4aff661f1f42\",\"screenshots@mozilla.org\":\"912d9c3d-a354-4480-8235-a34b849935ad\",\"webcompat-reporter@mozilla.org\":\"5ac469cd-6998-4e2e-bbcd-daa83e8ee912\",\"webcompat@mozilla.org\":\"7cec3fc9-172a-4aa3-9449-14efb1cd6228\",\"fxmonitor@mozilla.org\":\"1e7fb713-0aa5-45b7-8c31-c1118fe92152\"}");
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1544744278);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181207224003");
user_pref("media.gmp-manager.lastCheck", 1544895327);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "52c5b455-2d71-46b0-bf7f-bfde00af77ac");
user_pref("security.sandbox.plugin.tempDirSuffix", "d5280e53-c3fd-4075-9e82-f5dad8ba0b0b");
user_pref("services.blocklist.addons.checked", 1544894778);
user_pref("services.blocklist.gfx.checked", 1544894778);
user_pref("services.blocklist.onecrl.checked", 1544894778);
user_pref("services.blocklist.pinning.checked", 1544894778);
user_pref("services.blocklist.plugins.checked", 1544894778);
user_pref("services.settings.clock_skew_seconds", -49);
user_pref("services.settings.last_update_seconds", 1544894831);
user_pref("services.settings.main.language-dictionaries.last_check", 1544894778);
user_pref("services.settings.main.onboarding.last_check", 1544894778);
user_pref("services.settings.main.sites-classification.last_check", 1544894778);
user_pref("services.settings.main.tippytop.last_check", 1544894778);
user_pref("services.sync.engine.addresses.available", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1544895041);
user_pref("toolkit.telemetry.cachedClientID", "b15fa62b-679a-408e-b9de-9b23283a18de");
user_pref("toolkit.telemetry.previousBuildID", "20181207224003");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
